// FFT stage 1: 4 butterflies on pairs (0,4),(1,5),(2,6),(3,7). Twiddle W8^0.
// Inputs/outputs are 8 Q1.15 complex samples as flat buses.
module fft_stage1 (
    input  signed [127:0] xre_flat, xim_flat,
    output signed [127:0] s1re_flat, s1im_flat
);
    reg signed [15:0] temp_re, temp_im;
    reg [3:0] 		  i;
    reg [7:0] 		  j;
    reg [7:0] 		  k;
    reg [7:0] 		  m;
    reg [15:0] 		  re_temp;
    reg [15:0] 		  im_temp;
    reg [127:0] 	  re_cast, im_cast;
    reg 			  startfft;
    reg 			  clk_count_fft;
    reg [4:0] 		  count_fft;
    reg 			  clk_count_fft_pulse;
    reg [4:0] 		  count_fft_pulse;
    reg 			  clk_fft_pulse;
    reg 			  clk_out_fft_pulse;
    reg 			  rst_fft;
    reg 			  rst_fft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_count_fft_pulse;
    reg 			  startfft_pulse;
    reg 			  clk_
endmodule
