// SHA-256 Sigma/Ch/Maj functions. All 32-bit. Used in message schedule and compression.
// SIGMA0=ROTR2^ROTR13^ROTR22, SIGMA1=ROTR6^ROTR11^ROTR25.
// sigma0=ROTR7^ROTR18^SHR3, sigma1=ROTR17^ROTR19^SHR10.
module sha256_sigma (
    input  [31:0] a, b, c,
    output [31:0] SIGMA0_a, SIGMA1_a, sigma0_b, sigma1_b, Ch_abc, Maj_abc
);
    assign SIGMA0_a = {a[31:24], b[31:24], c[31:24]};
    assign SIGMA1_a = {a[23:16], b[23:16], c[23:16]};
    assign sigma0_b = {a[15:8], b[15:8], c[15:8]};
    assign sigma1_b = {a[7:0], b[7:0], c[7:0]};
    assign Ch_abc = SIGMA0_a + SIGMA1_a;
    assign Maj_abc = SIGMA0_a * SIGMA1_a;
endmodulemodule sha256_tb ();
    reg clk, reset;
    reg [31:0] blk_i, blk_o;
    reg [7:0] l, n;
    reg [31:0] block_512;
    reg [31:0] block_512_out;
    reg [31:0] tmp,tmp2,tmp3, tmp4;
    reg [31:0] h0,h1,h2,h3,h4,h5,h6,h7;
    reg [31:0] a,b,c,d,e,f,g,h;
    reg [31:0] a_out, b_out, c_out, d_out, e_out, f_out, g_out, h_out;
    reg [31:0] a_in, b_in, c_in, d_in, e_in, f_in, g_in, h_in;
    reg [3:0] counter;
    reg [31:0] block_512_new;
    reg [31:0] reg_L_out, reg_N_out;
    reg start_in;
    reg [31:0] length_out;
    reg [31:0] reg_block_out;
    reg [31:0] reg_h0_out, reg_h1_out, reg_h2_out, reg_h3_out, reg_h4_out, reg_h5_out, reg_h6_out, reg_h7_out;
    reg done_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in;
    // reg [31:0] length_out;
    // reg [31:0] reg_L_out, reg_N_out;
    // reg start_in
endmodule
