#!/usr/bin/env python3
"""
evaluate_syntax.py — HierRTLBench Syntax Pass-Rate Evaluator
=============================================================
Measures iverilog syntax pass rates matching the paper's methodology:

  HIERARCHICAL: each individual submodule .v file is checked independently
                (per-submodule-file metric, denominator = number of .v files)
  UNIFIED:      each unified .v file is checked independently
                (per-file metric, denominator = 14 modules)

This per-file approach is consistent with the paper's reported numbers:
  VeriGen-2B  ~44%  | VeriGen-6B  0%  | VeriGen-16B ~54% (hierarchical)

Usage:
    # Validate pre-generated outputs (default paths)
    python evaluate_syntax.py

    # Specify custom paths
    python evaluate_syntax.py \\
        --hier_dir    vgen_project/verigen_out \\
        --unified_dir vgen_project/unified_outputs \\
        --tb_dir      vgen_project/verigen_testbenches/verigen_testbenches \\
        --models 2B 6B 16B

    # Validate a single model only
    python evaluate_syntax.py --models 2B
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# ── Module metadata ───────────────────────────────────────────────────────────
# Maps module short-name (folder) to a human-readable label.
MODULES = [
    ("m01_alu",    "ALU"),
    ("m02_regfile","Register File"),
    ("m03_uart",   "UART TX"),
    ("m04_cpu",    "Multi-Cycle CPU"),
    ("m05_ctrl",   "Control Unit"),
    ("m06_riscv",  "Pipeline CPU"),
    ("m07_cache",  "D-Cache"),
    ("m08_arbiter","Round-Robin Arbiter"),
    ("m09_aes",    "AES-128 Enc"),
    ("m10_sha256", "SHA-256"),
    ("m11_crc32",  "CRC-32"),
    ("m12_fft",    "FFT-8"),
    ("m13_matmul", "MatMul-16"),
    ("m14_sort",   "Bubble Sort"),
]

# Unified output filenames (one .v per module)
UNIFIED_FILES = [
    "m01_alu.v",
    "m02_regfile.v",
    "m03_uart_tx.v",
    "m04_multicycle_cpu.v",
    "m05_control_unit.v",
    "m06_pipeline_cpu.v",
    "m07_dcache.v",
    "m08_round_robin_arb.v",
    "m09_aes128_enc.v",
    "m10_sha256.v",
    "m11_crc32.v",
    "m12_fft8.v",
    "m13_matmul16.v",
    "m14_bubble_sort.v",
]


def check_iverilog() -> bool:
    """Return True if iverilog is available on PATH."""
    try:
        result = subprocess.run(
            ["iverilog", "-V"],
            capture_output=True, text=True
        )
        return result.returncode == 0 or "Icarus Verilog" in (result.stdout + result.stderr)
    except FileNotFoundError:
        return False


def iverilog_check_file(verilog_file: str) -> tuple[bool, str]:
    """
    Run `iverilog -tnull` on a SINGLE file independently.
    Returns (passed: bool, first_error: str).
    """
    cmd = ["iverilog", "-tnull", verilog_file]
    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=30
        )
        passed = result.returncode == 0
        first_err = next(
            (l for l in result.stderr.splitlines() if "error:" in l), ""
        )
        return passed, first_err.strip()
    except subprocess.TimeoutExpired:
        return False, "timeout"
    except Exception as exc:
        return False, str(exc)


def evaluate_model(
    model: str,
    hier_dir: Path,
    unified_dir: Path,
    tb_dir: Path,
    verbose: bool = False,
) -> dict:
    """
    Evaluate syntax pass rates for a single model.

    Hierarchical: each LLM-generated submodule .v file is checked independently.
                  Integration files (*_integration.v) are excluded — they are
                  written deterministically by write_integrations.py, not by the LLM.
    Unified:      each unified .v file is checked independently.

    Pass criterion: iverilog -tnull exits with return code 0.
    Note: iverilog reports "syntax error\\nI give up." (no colon) for parse errors,
    so string matching on "error:" is insufficient — returncode must be used.

    Returns a dict:
      'hierarchical': list of (subfile_path, module_label, passed, first_error)
      'unified':      list of (module_label, passed, first_error)
      'hier_by_module': dict module_label -> (passed_files, total_files)
    """
    results: dict = {"hierarchical": [], "unified": [], "hier_by_module": {}}

    for idx, (folder, label) in enumerate(MODULES):
        # ── Hierarchical: per-submodule-file (LLM-generated only) ────────────
        mod_path = hier_dir / model / folder
        if mod_path.exists():
            # Exclude *_integration.v — those are deterministically written,
            # not generated by the LLM under evaluation.
            sub_files = sorted(
                f for f in mod_path.glob("*.v")
                if "integration" not in f.name
            )
        else:
            sub_files = []

        mod_pass = 0
        mod_total = len(sub_files)
        for f in sub_files:
            ok, err = iverilog_check_file(str(f))
            results["hierarchical"].append((str(f), label, ok, err))
            if ok:
                mod_pass += 1
            if verbose:
                status = "PASS" if ok else "FAIL"
                print(f"  [Hier/{model}/{folder}/{f.name}] {status}"
                      + (f" — {err}" if not ok and err else ""))

        results["hier_by_module"][label] = (mod_pass, mod_total)

        # ── Unified: per-file ─────────────────────────────────────────────────
        u_path = unified_dir / model / UNIFIED_FILES[idx]
        if u_path.exists():
            ok_u, err_u = iverilog_check_file(str(u_path))
        else:
            ok_u, err_u = False, "output file missing"
        results["unified"].append((label, ok_u, err_u))
        if verbose:
            status = "PASS" if ok_u else "FAIL"
            print(f"  [Unif/{model}/{UNIFIED_FILES[idx]}] {status}"
                  + (f" — {err_u}" if not ok_u and err_u else ""))

    return results


def print_summary(all_results: dict, models: list[str]) -> None:
    """Print a formatted summary table matching the paper."""

    # ── Hierarchical: per-submodule-file ──────────────────────────────────────
    print(f"\n{'='*62}")
    print("  Hierarchical Generation — Syntax Pass Rate")
    print("  (each individual submodule .v file checked independently)")
    print(f"{'='*62}")
    header = f"{'Model':<8}  {'Passed':>10}  {'Total files':>11}  {'Rate':>8}"
    print(header)
    print("-" * len(header))
    for model in models:
        if model not in all_results:
            continue
        rows = all_results[model]["hierarchical"]
        passed = sum(1 for _, _, ok, _ in rows if ok)
        total  = len(rows)
        rate   = passed / total * 100 if total else 0
        print(f"{model:<8}  {passed:>6}/{total:<4}  {total:>11}  {rate:>7.1f}%")
    print("-" * len(header))
    print()

    # ── Unified: per-file ─────────────────────────────────────────────────────
    total_u = len(MODULES)
    print(f"{'='*62}")
    print("  Unified Generation — Syntax Pass Rate")
    print("  (each unified .v file checked independently)")
    print(f"{'='*62}")
    header_u = f"{'Model':<8}  {'Passed':>8}  {'Total':>6}  {'Rate':>8}"
    print(header_u)
    print("-" * len(header_u))
    for model in models:
        if model not in all_results:
            continue
        rows = all_results[model]["unified"]
        passed = sum(1 for _, ok, _ in rows if ok)
        rate   = passed / total_u * 100 if total_u else 0
        print(f"{model:<8}  {passed:>4}/{total_u:<3}  {total_u:>6}  {rate:>7.1f}%")
    print("-" * len(header_u))
    print()

    # ── Per-module breakdown (hierarchical) ───────────────────────────────────
    print(f"{'='*62}")
    print("  Per-Module Breakdown — Hierarchical (subfiles pass/total)")
    print(f"{'='*62}")
    col_w = 14
    mod_header = f"{'Module':<22}" + "".join(f"  {m:<{col_w}}" for m in models)
    print(mod_header)
    print("-" * len(mod_header))
    for _, label in MODULES:
        row = f"{label:<22}"
        for model in models:
            if model not in all_results:
                row += "  " + "-" * col_w
                continue
            p, t = all_results[model].get("hier_by_module", {}).get(label, (0, 0))
            cell = f"{p}/{t} {'PASS' if p==t and t>0 else ''}"
            row += f"  {cell:<{col_w}}"
        print(row)
    print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="HierRTLBench syntax pass-rate evaluator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--hier_dir",
        default="vgen_project/verigen_out",
        help="Root of hierarchical outputs (default: vgen_project/verigen_out)",
    )
    parser.add_argument(
        "--unified_dir",
        default="vgen_project/unified_outputs",
        help="Root of unified outputs (default: vgen_project/unified_outputs)",
    )
    parser.add_argument(
        "--tb_dir",
        default="vgen_project/verigen_testbenches/verigen_testbenches",
        help="Root of testbench directory (not used for syntax-only checks, reserved for future use)",
    )
    parser.add_argument(
        "--models",
        nargs="+",
        default=["2B", "6B", "16B"],
        choices=["2B", "6B", "16B"],
        metavar="MODEL",
        help="Model sizes to evaluate (default: 2B 6B 16B)",
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Print per-file pass/fail details",
    )
    args = parser.parse_args()

    # ── Dependency check ──────────────────────────────────────────────────────
    if not check_iverilog():
        print("ERROR: iverilog not found on PATH.", file=sys.stderr)
        print("  Ubuntu/Debian : sudo apt-get install iverilog", file=sys.stderr)
        print("  macOS         : brew install icarus-verilog", file=sys.stderr)
        sys.exit(1)

    hier_dir    = Path(args.hier_dir)
    unified_dir = Path(args.unified_dir)
    tb_dir      = Path(args.tb_dir)

    all_results: dict = {}

    for model in args.models:
        print(f"\nEvaluating model: {model} ...")
        all_results[model] = evaluate_model(
            model, hier_dir, unified_dir, tb_dir, verbose=args.verbose
        )

    print_summary(all_results, args.models)

    # ── Exit code: 0 if any hierarchical file passes (at least one model) ──────
    any_pass = any(
        ok
        for model_res in all_results.values()
        for _, _, ok, _ in model_res["hierarchical"]
    )
    sys.exit(0 if any_pass else 1)


if __name__ == "__main__":
    main()
