// Multi-cycle Harvard RISC CPU. 5-phase FSM (IF/ID/EX/MEM/WB). ADD/SUB/AND/OR/ADDI/LW/SW/BEQ.
module multicycle_cpu (
    input clk, rst
);
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
    // Instruction memory
endmodule
