// Data memory: 256x32-bit words. Synchronous write on mem_we. Asynchronous read.
module cpu_dmem (
    input        clk,
    input [31:0] addr, wdata,
    input        mem_we,
    output [31:0] rdata
);
    reg [31:0] dmem [255:0];
    initial $readmemh("dmem_per_line.txt", dmem);
    assign rdata = dmem[addr[31:2]];
endmodule
`timescale 1ns / 1ps

module cpu_testbench ();
    reg        clk;
    reg        reset;
    reg        mem_en;
    reg [31:0] mem_addr;
    reg [31:0] mem_rdata;
    reg [31:0] mem_wdata;
    wire [31:0] cpu_rdata;
    wire        cpu_done;
    wire [31:0] cpu_addr;
    wire        cpu_mem_en;
    wire [31:0] cpu_mem_addr;
    wire [31:0] cpu_mem_rdata;
    wire [31:0] cpu_mem_wdata;
    
    integer     pipe_out;
    integer     pipe_in;
    
    integer     data_in;
    integer     data_out;
    
    integer     A_count;
    integer     A_count2;
    integer     A_count3;
    integer     A_count4;
    integer     A_count5;
    integer     A_count6;
    integer     A_count7;
    integer     A_count8;
    integer     A_count9;
    integer     A_count10;
    integer     A_count11;
    integer     A_count12;
    integer     A_count13;
    integer     A_count14;
    integer     A_count15;
    integer     A_count16;
    integer     A_count17;
    integer     A_count18;
    integer     A_count19;
    integer     A_count20;
    integer     A_count21;
    integer     A_count22;
    integer     A_count23;
    integer     A_count24;
    integer     A_count25;
    integer     A_count26;
    integer     A_count27;
    integer     A_count28;
    integer     A_count29;
    integer     A_count30;
    integer     A_count31;
    integer     A_count32;
    integer     A_count33;
    integer     A_count34;
    integer     A_count35;
    integer     A_count36;
    integer     A_count37;
    integer     A_count38;
    integer     A_count39;
    integer     A_count40;
    integer     A_count41;
    integer     A_count42;
    integer     A_count43;
    integer     A_count44;
    integer     A_count45;
    integer     A_count46;
    integer     A_count47;
    integer     A_count48;
    integer     A_count49;
    integer     A_count50;
    integer     A_count51;
    integer     A_count52;
    integer     A_count53;
    integer     A_count54;
    integer     A_count55;
    integer     A_count56;
    integer     A_count57;
    integer     A_count58;
    integer     A_count59;
    integer     A_count60;
    integer     A_count61;
    integer     A_count62;
    integer     A_count63;
    integer     A_count64;
    integer     A_count65;
    integer     A_count66;
    integer     A_count67;
    integer     A_count68;
    integer     A_count69;
    integer     A_count70;
    integer     A_count71;
    integer     A_count72;
    integer     A_count73;
    integer     A_count74;
    integer     A_count75;
    integer     A_count76;
    integer     A_count77;
    integer     A_count78;
    integer     A_count79;
    integer     A_count80;
    integer     A_count81;
    integer     A_count82;
    integer     A_count83;
    integer     A_count84;
    integer     A_count85;
    integer     A_count86;
    integer     A_count87;
    integer     A_count88;
    integer     A_count89;
    integer     A_count90;
    integer     A_count91;
    integer     A_count92;
    integer     A_count93;
    integer     A_count94;
    integer     A_count95;
    integer     A_count96;
    integer     A_count97;
    integer     A_count98;
    integer     A_count99;
    integer     A_count100;
    integer     A_count101;
    integer     A_count102;
    integer     A_count103;
    integer     A_count104;
    integer     A_count105;
    integer     A_count106;
    integer     A_count107;
    integer     A_count108;
    integer     A_count109;
    integer     A_count110;
    integer     A_count111;
    integer     A_count112;
    integer     A_count113;
    integer     A_count114;
    integer     A_count115;
    integer     A_count116;
    integer     A_count117;
    integer     A_count118;
    integer     A_count119;
    integer     A_count120;
    integer     A_count121;
    integer     A_count122;
    integer     A_count123;
    integer     A_count124;
    integer     A_count125;
    integer     A_count126;
    integer     A_count127;
    integer     A_count128;
    integer     A_count129;
    integer     A_count130;
    integer     A_count131;
    integer     A_count132;
    integer     A_count133;
    integer     A_count134;
    integer     A_count135;
    integer     A_count136;
    integer     A_count137;
    integer     A_count138;
    integer     A_count139;
    integer     A_count140;
    integer     A_count141;
    integer     A_count142;
    integer     A_count143;
    integer     A_count144;
    integer     A_count145;
    integer     A_count146;
    integer     A_count147;
    integer     A_count148;
    integer     A_count149;
    integer     A_count150;
    integer     A_count151;
    integer     A_count152;
    integer     A_count153;
    integer     A_count154;
    integer     A_count155;
    integer     A_count156;
    integer     A_count157;
    integer     A_count158;
    integer     A_count159;
    integer     A_count160;
    integer     A_count161;
    integer     A_count162;
    integer     A_count163;
    integer     A_count164;
    integer     A_count165;
    integer     A_count166;
    integer     A_count167;
    integer     A_count168;
    integer     A_count169;
    integer     A_count170;
    integer     A_count171;
    integer     A_count172;
    integer     A_count173;
    integer     A_count174;
    integer     A_count175;
    integer     A_count176;
    integer     A_count177;
    integer     A_count178;
    integer     A_count179;
    integer     A_count180;
    integer     A_count181;
    integer     A_count182;
    integer     A_count183;
    integer     A_count184;
    integer     A_count185;
    integer     A_count186;
    integer     A_count187;
    integer     A_count188;
    integer     A_count189;
    integer     A_count190;
    integer     A_count191;
    integer
endmodule
