// UART TX FSM. States: IDLE->START->DATA(8 bits)->STOP->IDLE. Driven by baud tick.
module uart_tx_fsm (
    input      clk, rst, tick, tx_start,
    output reg load, shift_en, tx_out, busy
);
    reg [2:0] state, next_state;
    parameter IDLE      = 3'b000;
    parameter START     = 3'b001;
    parameter DATA      = 3'b010;
    parameter STOP      = 3'b011;
    parameter END       = 3'b100;
    reg [2:0]   r_reg_state;
    reg [7:0]   r_reg_data;
    reg [2:0]   r_reg_bit_cnt;
    reg [7:0]   r_reg_stop_cnt;
    reg         r_reg_tx_en;
    reg         r_reg_start_bit;
    reg [7:0]   r_reg_data_bit;
    reg [7:0]   r_reg_parity_bit;
    reg [3:0]   r_reg_stop_bit;
    reg [2:0]   r_reg_baud_cnt;
    reg [7:0]   r_reg_uart_state;
    reg         r_reg_uart_txd;
    reg         r_reg_uart_start;
    reg [7:0]   r_reg_uart_out;
    reg         r_reg_uart_busy;
    always @(*) begin
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_baud_cnt         = 0;
        r_reg_bit_cnt          = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_data_bit        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_start_bit       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity_bit  = 0;
        r_reg_data_bit        = 0;
        r_reg_parity_bit       = 0;
        r_reg_stop_bit        = 0;
        r_reg_stop_cnt         = 0;
        r_reg_parity_bit       = 0;
        r_reg_baud_cnt         = 0;
        r_reg_uart_state       = 0;
        r_reg_uart_txd         = 0;
        r_reg_uart_start       = 0;
        r_reg_uart_out         = 0;
        r_reg_uart_busy        = 0;
        r_reg_uart_busy        = 0;
        r_reg_data_parity
endmodule
