// N-bit ALU. op: 3'b000=ADD, 001=SUB, 010=AND, 011=OR, 100=XOR, 101=SHL.
// Synchronous reset. Registered outputs: result, zero_flag, carry_flag.
module alu #(parameter N = 8) (
    input              clk, rst,
    input  [N-1:0]     a, b,
    input  [2:0]       op,
    output reg [N-1:0] result,
    output reg         zero_flag,
    output reg         carry_flag
);
    reg [N-1:0] b_xor;
    reg [N-1:0] b_and;
    reg [N-1:0] b_or;
    reg [N-1:0] b_add;
    reg [N-1:0] b_sub;
    reg [N-1:0] b_shl;
    reg [N-1:0] b_shr;
    reg [N-1:0] b_not;
    reg [N-1:0] b_load;
    reg [N-1:0] b_store;
    reg [N-1:0] b_load_not;
    reg [N-1:0] b_store_not;
    reg [N-1:0] b_add_not;
    reg [N-1:0] b_sub_not;
    reg [N-1:0] b_shl_not;
    reg [N-1:0] b_shr_not;
    reg [N-1:0] b_and_not;
    reg [N-1:0] b_or_not;
    reg [N-1:0] b_xor_not;
    reg [N-1:0] b_load_xor;
    reg [N-1:0] b_store_xor;
    reg [N-1:0] b_load_and;
    reg [N-1:0] b_store_and;
    reg [N-1:0] b_load_or;
    reg [N-1:0] b_store_or;
    reg [N-1:0] b_load_not_xor;
    reg [N-1:0] b_store_not_xor;
    reg [N-1:0] b_load_not_and;
    reg [N-1:0] b_store_not_and;
    reg [N-1:0] b_load_not_or;
    reg [N-1:0] b_store_not_or;
    reg [N-1:0] b_load_xor_and;
    reg [N-1:0] b_store_xor_and;
    reg [N-1:0] b_load_xor_or;
    reg [N-1:0] b_store_xor_or;
    reg [N-1:0] b_load_not_xor_and;
    reg [N-1:0] b_store_not_xor_and;
    reg [N-1:0] b_load_not_xor_or;
    reg [N-1:0] b_store_not_xor_or;
    reg [N-1:0] b_load_and_xor;
    reg [N-1:0] b_store_and_xor;
    reg [N-1:0] b_load_or_xor;
    reg [N-1:0] b_store_or_xor;
    reg [N-1:0] b_load_not_and_xor;
    reg [N-1:0] b_store_not_and_xor;
    reg [N-1:0] b_load_not_or_xor;
    reg [N-1:0] b_store_not_or_xor;
    reg [N-1:0] b_load_xor_and_or;
    reg [N-1:0] b_store_xor_and_or;
    reg [N-1:0] b_load_xor_or_and;
    reg [N-1:0] b_store_xor_or_and;
    reg [N-1:0] b_load_not_xor_and_or;
    reg [N-1:0] b_store_not_xor_and_or;
    reg [N-1:0] b_load_not_xor_or_and;
    reg [N-1:0] b_store_not_xor_or_and;
    reg [N-1:0] b_load_and_xor_or;
    reg [N-1:0] b_store_and_xor_or;
    reg [N-1:0] b_load_or_xor_or;
    reg [N-1:0] b_store_or_xor_or;
    reg [N-1:0] b_load_not_and_xor_or;
    reg [N-1:0] b_store_not_and_xor_or;
    reg [N-1:0] b_load_not_or_xor_or;
    reg [N-1:0] b_store_not_or_xor_or;
    reg [N-1:0] b_load_xor_and_or_and;
    reg [N-1:0] b_store_xor_and_or_and;
    reg [N-1:0] b_load_xor_or_and_and;
    reg [N-1:0] b_store_xor_or_and_and;
    reg [N-1:0] b_load_not_xor_and_or_and;
    reg [N-1:0] b_store_not_xor_and_or_and;
    reg [N-1:0] b_load_not_or_xor_or_and;
    reg [N-1:0] b_store_not_or_xor_or_and;
    reg [N-1:0] b_load_xor_and_or_or;
    reg [N-1:0] b_store_xor_and_or_or;
    reg [N-1:0] b_load_xor_or_and_or;
    reg [N-1:0] b_store_xor_or_and_or;
    reg [N-1:0] b_load_not_xor_and_or_or;
    reg [N-1:0] b_store_not_xor_and_or_or;
    reg [N-1:0] b_load_not_or_xor_or_or;
    reg [N-1:0] b_store_not_or_xor_or_or;
    reg [N-1:0] b_load_xor_and_or_and_and;
    reg [N-1:0] b_store_xor_and_or_and_and;
    reg [N-1:0] b_load_xor_or_and_and_and;
    reg [N-1:0] b_store_xor_or_and_and_and;
    reg [N-1:0] b_load_not_xor_and_or_or_and;
    reg [N-1:0] b_store_not_xor_and_or_or_and;
    reg [N-1:0] b_load_not_or_xor_or_or_and;
    reg [N-1:0] b_store_not_or_xor_or_or_and;
    reg [N-1:0] b_load_xor_and_or_or_or;
    reg [N-1:0] b_store_xor_and_or_or_or;
    reg [N-1:0] b_load_xor_or_and_or_or;
    reg [N-1:0] b_store_xor_or_and_or_or;
    reg [N-1:0] b_load_not_xor_and_or_or_or;
    reg [N-1:0] b_store_not_
endmodule
