// Dot product of a 16-element row vector with a 16-element column vector.
// 16-bit unsigned elements. 32-bit accumulator. Takes 16 cycles after start.
module mat_row (
    input         clk, rst, start,
    input  [255:0] row_a_flat,
    input  [255:0] col_b_flat,
    output [31:0]  result,
    output         done
);
    // localparams
    localparam ROW_WIDTH = `PRECISION_ROW;
    localparam COL_WIDTH = `PRECISION_COL;
    localparam MATRIX_SIZE = `PRECISION_COL;
    localparam ROW_SIZE = (1 << ROW_WIDTH);
    localparam COL_SIZE = (1 << COL_WIDTH);
    localparam MEM_SIZE = (ROW_SIZE * COL_SIZE);
    localparam MEM_WIDTH = `PRECISION_MEM;
    localparam MEM_POINT = `PRECISION_MEM-1;
    localparam DIV_LOG2 = `PRECISION_COL-`PRECISION_MEM+1;
    localparam DIV_PRECISION = (DIV_LOG2 == 0) ? 1 : DIV_LOG2;
    localparam DIV_WIDTH = `PRECISION_DIV;
    localparam DIV_POINT = `PRECISION_DIV-1;
    localparam DIV_PRECISION_ROW = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_COL = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_MEM = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_DIV = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_MAX = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_POW = DIV_PRECISION + DIV_POINT;
    localparam DIV_PRECISION_MAX_POW = DIV_PRECISION_POW + DIV_PRECISION_DIV;
    localparam DIV_PRECISION_MAX_POW_ROW = DIV_PRECISION_MAX_POW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL = DIV_PRECISION_MAX_POW + DIV_PRECISION_COL;
    localparam DIV_PRECISION_MAX_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL = DIV_PRECISION_MAX_POW_COL + DIV_PRECISION_COL;
    localparam DIV_PRECISION_MAX_POW_COL_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_POW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_COL;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_POW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_COL;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_POW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW_COL = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_COL;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_ROW;
    localparam DIV_PRECISION_MAX_POW_COL_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_COL_ROW_POW_COL_ROW = DIV_PRECISION_MAX_POW_COL_COL_COL_ROW + DIV_PRECISION_
endmodule
